### ISSUE TITLE
contrat d'assistance technnique périmé

### ISSUE THREAD

**Issue by BenjaminLesne** [freelance-info/contracts#1]
Le contrat d'assistance technique a [cette source](http://lthoumyre.chez.com/pro/1/ctra19980702.htm#2a) qui date de 1998.

Où on peut par exemple lire :
```
Le prix de l’assistance technique est [...] en francs français et hors taxes.
```

Je pense qu'il faudrait au moins le préciser à coté de la source dans assistance-technique.md  et assistance-technique-freelance.md.
Voir même supprimer ces deux contrats car probablement périmés depuis plus 20 ans

PS: Merci beaucoup pour le partage des contrats ça m'aide beaucoup !

**Comment by bcaure** [comment]
En effet, ce contrat est assez ancien et il y a sans doute pas mal de parties à mettre à jour. Je vais le préciser et modifier la partie en franc... Merci pour ton retour
